spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8081